@URL_BASE = http://localhost:8080

@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJpZCI6IjhjOTllNTc0LTFhZjQtNDUzMi1hOTQ4LTE4Y2E0NTJhNmFlNSIsInVzZXJuYW1lIjoiamFtZXMyQGdtYWlsLmNvbSIsImlhdCI6MTY4NTY3MTkxNSwiZXhwIjoxNjg1Njc1NTE1LCJpc3MiOiJVVEZQUiJ9.a1Obk3sX6f-bsXhmE9_nJtKly5gqrfZDlBarHTymeec

### Criar Pedido
POST {{URL_BASE}}/pedido
Content-Type: application/json
Authorization: {{token}}

{
	"isopen": true,
	"carrinhoId": "60599a6a-2b33-4189-9fce-35841b557105"
}

### Obter um pedido pelo ID
GET {{URL_BASE}}/pedido/5d0e8ae2-3392-4c2f-8626-181849847124
Authorization: {{token}}

### Obter todos pedidos
GET {{URL_BASE}}/pedido
Authorization: {{token}}

### Atualizar Pedido
PUT {{URL_BASE}}/pedido/5d0e8ae2-3392-4c2f-8626-181849847124
Content-Type: application/json
Authorization: {{token}}

{
	"isopen": true,
	"carrinhoId": "fd7c78fb-493b-488e-9a46-b59d4e72801f"
}